### PR TITLE
User sees navbar

### PR DESCRIPTION
**Pull request by descholar-ceo**
#### What does this PR ​ do​ ?
It allows users to see tha navigation bar which helps them to navigate through the app so easily

#### Description of Task to be completed?
* -Create component of navbar
*  -Add redux for state management
*  -Change login system to use redux store

#### How should this be manually tested?
* Clone this repository by `git clone https://github.com/descholar-ceo/find-flight-info`
* Type these commands : 
    *  `cd find-flight-info` to go in the root directory of the project
    * `git pull origin ft-navbar` to pull this branch
    * `npm install` or `yarn add` to install all the packages
    * `npm start` or `yarn start`
* Then go in the browser, you will see a default opened page is signup with the navigation bar above

#### Any background context you want to provide?
* You have to install [nodejs](https://nodejs.org/en/) version 6 or higher prior to test this application

#### Screenshots (​ if​ appropriate)
05 navbar

06 navbar

#### Questions:
No Question

### CODE REVIEW

**Comment by the22mastermind** [comment]
Awesome job bro. However I have a few question, I cloned your repo and when I run it locally I don't see the navbar as described in this PR. Same for redux. Do you know why that is?

**Comment by descholar-ceo** [comment]
@the22mastermind I updated the PR I forgot to add this command `git pull origin ft-navbar to pull this branch` so that you will be able to get whatever is written in this PR

**Comment by descholar-ceo** [comment]
@the22mastermind I updated the PR I forgot to add this command `git pull origin ft-navbar to pull this branch` so that you will be able to get whatever is written in this PR

**Comment by descholar-ceo** [comment]
@the22mastermind I updated the PR I forgot to add this command `git pull origin ft-navbar to pull this branch` so that you will be able to get whatever is written in this PR

**Comment by the22mastermind** [comment]
Well done Emmanuel! You're good to go.

**Pull request merged**
